spring.application.name=microservicio-ep2
server.port=8080

# Actuator: expone endpoints de salud y métricas
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always

# Prometheus: habilita métricas con etiquetas de la aplicación
management.metrics.tags.application=${spring.application.name}